### PR TITLE
Fixes type hint non using direct import from 'multiprocessing'

### LINKED ISSUE #151: awswrangler import error on python:3.7 dockers
on python:3.7-slim, python:3.7 and python:3.8 import awswrangler suddenly starts failing.

pip3 install --no-cache-dir --trusted-host pypi.python.org awswrangler

Behavior:

import awswrangler as wr

Error:

from awswrangler.pandas import Pandas  # noqa
File "/usr/local/lib/python3.7/site-packages/awswrangler/pandas.py", line 45, in
class Pandas:
File "/usr/local/lib/python3.7/site-packages/awswrangler/pandas.py", line 273, in Pandas
def _read_csv_once_remote(send_pipe: mp.connection.Connection, session_primitives: "SessionPrimitives",
AttributeError: module 'multiprocessing' has no attribute 'connection'

this works fine with image python:3.6

also posted at: https://github.com/docker-library/python/issues/461

### PR DESCRIPTION
**Pull request by phakiller**
*Issue #151*

*Description of changes:*

In python 3.7 or above people get the error:
`AttributeError: module 'multiprocessing' has no attribute 'connection'`

To fix this, instead of using `mp.connection.Connection` to make the Type Hints now we import `Connection` from `multiprocessing.connection`:
```python3
from multiprocessing.connection import Connection
```
And to be more meaningful `Connection` was aliased as `MultiprocessingConnection`.

In some circumstances a get the same error using Python 3.6.9 on Manjaro, but using the same Python version on Ubuntu works and these changes fix for these cases as well.

Closes #151 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by igorborgest** [comment]
@phakiller awesome! Thank you!
