### ISSUE TITLE
[ERROR] AttributeError: module 'awswrangler.s3' has no attribute 'read_excel'

### ISSUE THREAD

**Issue by kev-dfs** [awslabs/aws-data-wrangler#523]
Hi,

I'm trying read an Excel file from a s3 bucket with the next code:

`bucket = 'my_bucket'`
`key = 'my_file.xlsx'`
`df = wr.s3.read_excel(f's3://{bucket}/{key}')`

This code is running on a Lambda with Python 3.7 and layer awswrangler versión 2.2.0

This code generate an error... 
`[ERROR] AttributeError: module 'awswrangler.s3' has no attribute 'read_excel' `

Please I need help.
Regards.

**Comment by maxispeicher** [comment]
Excel support was released with version `2.3.0`, so `read_excel` didn't exist in `2.2.0`. Can you try using the whl for the new release and check again if it works?

**Comment by kev-dfs** [comment]
Hi @maxispeicher,

This work fine with `2.3.0`, thanks you
