### ISSUE TITLE
awswrangler import error on python:3.7 dockers

### ISSUE THREAD

**Issue by brandonwbrown** [awslabs/aws-data-wrangler#151]
on python:3.7-slim, python:3.7 and python:3.8 import awswrangler suddenly starts failing.

pip3 install --no-cache-dir --trusted-host pypi.python.org awswrangler

Behavior:

import awswrangler as wr

Error:

from awswrangler.pandas import Pandas  # noqa
File "/usr/local/lib/python3.7/site-packages/awswrangler/pandas.py", line 45, in
class Pandas:
File "/usr/local/lib/python3.7/site-packages/awswrangler/pandas.py", line 273, in Pandas
def _read_csv_once_remote(send_pipe: mp.connection.Connection, session_primitives: "SessionPrimitives",
AttributeError: module 'multiprocessing' has no attribute 'connection'

this works fine with image python:3.6

also posted at: https://github.com/docker-library/python/issues/461

**Comment by dicoinfo26** [comment]
I have the same problem using version 0.2.6, I changed my dockerfile to the current version and the error persists when importing the library.

**Comment by igorborgest** [comment]
Thanks guys! The fix will be released among several others improvements in the version `1.0.0` April 10th!
